from usage import *

Digitizer = Usage("digitizers.Digitizer", 0xd0001, CA)
Pen = Usage("digitizers.Pen", 0xd0002, CA)
LightPen = Usage("digitizers.LightPen", 0xd0003, CA)
TouchScreen = Usage("digitizers.TouchScreen", 0xd0004, CA)
TouchPad = Usage("digitizers.TouchPad", 0xd0005, CA)
WhiteBoard = Usage("digitizers.WhiteBoard", 0xd0006, CA)
CoordinateMeasuringMachine = Usage("digitizers.CoordinateMeasuringMachine", 0xd0007, CA)
ThreeDDigitizer = Usage("digitizers.ThreeDDigitizer", 0xd0008, CA)
StereoPlotter = Usage("digitizers.StereoPlotter", 0xd0009, CA)
ArticulatedArm = Usage("digitizers.ArticulatedArm", 0xd000A, CA)
Armature = Usage("digitizers.Armature", 0xd000B, CA)
MultiplePointDigitizer = Usage("digitizers.MultiplePointDigitizer", 0xd000C, CA)
FreeSpaceWand = Usage("digitizers.FreeSpaceWand", 0xd000D, CA)
Stylus = Usage("digitizers.Stylus", 0xd0020, CL)
Puck = Usage("digitizers.Puck", 0xd0021, CL)
Finger = Usage("digitizers.Finger", 0xd0022, CL)
TipPressure = Usage("digitizers.TipPressure", 0xd0030, DV)
BarrelPressure = Usage("digitizers.BarrelPressure", 0xd0031, DV)
InRange = Usage("digitizers.InRange", 0xd0032, MC)
Touch = Usage("digitizers.Touch", 0xd0033, MC)
Untouch = Usage("digitizers.Untouch", 0xd0034, OSC)
Tap = Usage("digitizers.Tap", 0xd0035, OSC)
Quality = Usage("digitizers.Quality", 0xd0036, DV)
DataValid = Usage("digitizers.DataValid", 0xd0037, MC)
TransducerIndex = Usage("digitizers.TransducerIndex", 0xd0038, DV)
TabletFunctionKeys = Usage("digitizers.TabletFunctionKeys", 0xd0039, CL)
ProgramChangeKeys = Usage("digitizers.ProgramChangeKeys", 0xd003A, CL)
BatteryStrength = Usage("digitizers.BatteryStrength", 0xd003B, DV)
Invert = Usage("digitizers.Invert", 0xd003C, MC)
XTilt = Usage("digitizers.XTilt", 0xd003D, DV)
YTilt = Usage("digitizers.YTilt", 0xd003E, DV)
Azimuth = Usage("digitizers.Azimuth", 0xd003F, DV)
Altitude = Usage("digitizers.Altitude", 0xd0040, DV)
Twist = Usage("digitizers.Twist", 0xd0041, DV)
TipSwitch = Usage("digitizers.TipSwitch", 0xd0042, MC)
SecondaryTipSwitch = Usage("digitizers.SecondaryTipSwitch", 0xd0043, MC)
BarrelSwitch = Usage("digitizers.BarrelSwitch", 0xd0044, MC)
Eraser = Usage("digitizers.Eraser", 0xd0045, MC)
TabletPick = Usage("digitizers.TabletPick", 0xd0046, MC)

# HUTRR30
TouchValid = Usage("digitizers.TouchValid", 0xd0047, MC)
Width = Usage("digitizers.Width", 0xd0048, DV)
Height = Usage("digitizers.Height", 0xd0049, DV)

# HUTRR34
Contactidentifier = Usage("digitizers.Contactidentifier", 0xd0051, DV)
Deviceconfiguration = Usage("digitizers.Deviceconfiguration", 0xd000E, CA)
Devicemode = Usage("digitizers.Devicemode", 0xd0052, DV)
Deviceidentifier = Usage("digitizers.Deviceidentifier", 0xd0053, DV)
Contactcount = Usage("digitizers.Contactcount", 0xd0054, DV)
Contactcountmaximum = Usage("digitizers.Contactcountmaximum", 0xd0055, DV)
Devicesettings = Usage("digitizers.Devicesettings", 0xd0023, CL)

# HUTRR46
SecondaryBarrelSwitch = Usage("digitizers.SecondaryBarrelSwitch", 0xd005A, MC)
TransducerSerialNumber = Usage("digitizers.TransducerSerialNumber", 0xd005b, SV)

# HUTRR53
PreferredColor = Usage("digitizers.PreferredColor", 0xd005C, DV)
