from .usage import *

# HUTRR84

LampArray = Usage("lighting.LampArray", 0x590001, CA)
LampArrayAttributesReport = Usage("lighting.LampArrayAttributesReport", 0x590002, CL)
LampCount = Usage("lighting.LampCount", 0x590003, SV)
BoundingBoxWidthInMicrometers = Usage("lighting.BoundingBoxWidthInMicrometers", 0x590004, SV)
BoundingBoxHeightInMicrometers = Usage("lighting.BoundingBoxHeightInMicrometers", 0x590005, SV)
BoundingBoxDepthInMicrometers = Usage("lighting.BoundingBoxDepthInMicrometers", 0x590006, SV)
LampArrayKind = Usage("lighting.LampArrayKind", 0x590007, SV)
MinUpdateIntervalInMicroseconds = Usage("lighting. MinUpdateIntervalInMicroseconds", 0x590008, SV)
LampAttributesRequestReport = Usage("lighting.LampAttributesRequestReport", 0x590020, CL)
LampId = Usage("lighting.LampId", 0x590021, SV)
LampAttributesResponseReport = Usage("lighting.LampAttributesResponseReport", 0x590022, CL)
PositionXInMicrometers = Usage("lighting.PositionXInMicrometers", 0x590023, DV)
PositionYInMicrometers = Usage("lighting.PositionYInMicrometers", 0x590024, DV)
PositionZInMicrometers = Usage("lighting.PositionZInMicrometers", 0x590025, DV)
LampPurposes = Usage("lighting.LampPurposes", 0x590026, DV)
UpdateLatencyInMicroseconds = Usage("lighting.UpdateLatencyInMicroseconds", 0x590027, DV)
RedLevelCount = Usage("lighting.RedLevelCount", 0x590028, DV)
GreenLevelCount = Usage("lighting.GreenLevelCount", 0x590029, DV)
BlueLevelCount = Usage("lighting.BlueLevelCount", 0x59002A, DV)
IntensityLevelCount = Usage("lighting.IntensityLevelCount", 0x59002B, DV)
IsProgrammable = Usage("lighting.IsProgrammable", 0x59002C, DV)
InputBinding = Usage("lighting.InputBinding", 0x59002D, DV)
LampMultiUpdateReport = Usage("lighting.LampMultiUpdateReport", 0x590050, CL)
RedUpdateChannel = Usage("lighting.RedUpdateChannel", 0x590051, DV)
GreenUpdateChannel = Usage("lighting.GreenUpdateChannel", 0x590052, DV)
BlueUpdateChannel = Usage("lighting.BlueUpdateChannel", 0x590053, DV)
IntensityUpdateChannel = Usage("lighting.IntensityUpdateChannel", 0x590054, DV)
LampUpdateFlags = Usage("lighting.LampUpdateFlags", 0x590055, DV)
LampRangeUpdateReport = Usage("lighting.LampRangeUpdateReport", 0x590060, CL)
LampIdStart = Usage("lighting.LampIdStart", 0x590061, DV)
LampIdEnd = Usage("lighting.LampIdEnd", 0x590062, DV)
LampArrayControlReport = Usage("lighting.LampArrayControlReport", 0x590070, CL)
AutonomousMode = Usage("lighting.AutonomousMode", 0x590071, DV)
